language: node_js
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - '8'
before_script:
  - npm install
script:
  - xvfb-run npm run lint
#  - xvfb-run npm test
